env: "local" # local dev prod
storage_path: "user=gros password=grosBerg22 dbname=wb_db sslmode=disable" # Будет порт для постгреса
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
  user: "admin"
  password: "admin"

#"postgresql://gros:grosBerg22@:5432/wb_db?sslmode=disable" - alternative